#!/bin/bash

APP_DIR=$(dirname "$(readlink -f "${0}")")
export LD_LIBRARY_PATH="$APP_DIR/usr/lib:$LD_LIBRARY_PATH"
echo "Added local library path: $APP_DIR/usr/lib"
cd "$APP_DIR/usr/bin"
exec ./ScriptLauncher
